### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by anusha7530** [OpenTekHub/cryptobot#1]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

**Comment by neyhere07** [comment]
Hello Admin @Harish-2003, I'm a WOB Contributor-2024. I would like to add Code of Conduct to this repository. Please assign this issue to me. Thank you!

**Comment by neyhere07** [comment]
In Code of Conduct, e-mail id is need to be mention. Can you tell me which e-mail id should I mention?

**Comment by Harish-2003** [comment]
peddinaharish2003@gmail.com
