### ISSUE TITLE
Add github greetings bot

### ISSUE THREAD

**Issue by Harish-2003** [OpenTekHub/cryptobot#11]

**Comment by Harish-2003** [comment]
can someone tell me weather this greetings bot is working thank you if not then this issue is open please look into it and make necessary changes

**Comment by KiranBaliga** [comment]
Please assign this task to me as a part of WOB24 @Harish-2003 Thank you!

**Comment by Harish-2003** [comment]
Go ahead and make an pr

**Comment by KiranBaliga** [comment]
@Harish-2003 Please review the PR and share the feedback.

**Comment by Harish-2003** [comment]
The bot isn't creating an message while I making an issue

**Comment by KiranBaliga** [comment]
@Harish-2003 I will test it additionally. Sorry!

**Comment by KiranBaliga** [comment]
@Harish-2003 I have used a new testing account to test the message and it has worked. Because I have first-interaction script, it will display for someone who is raising an issue or PR for the first time in OpenTekHub Cryptobot Repo.

**Comment by Harish-2003** [comment]
@KiranBaliga the bot should respond every time when an user created an issue or raises an pr

**Comment by smartfellow1234** [comment]
hi can u please assign this project to me @Harish-2003

**Comment by Harish-2003** [comment]
> hi can u please assign this project to me @Harish-2003

Please make an pr

**Comment by smartfellow1234** [comment]
Done.

**Comment by smartfellow1234** [comment]
please checkout i have raised pr @Harish-2003

**Comment by smartfellow1234** [comment]
please check now @Harish-2003
