### ISSUE TITLE
Update readme file with the link of the telegram bot

### ISSUE THREAD

**Issue by Harish-2003** [OpenTekHub/cryptobot#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Update readme file with the link of the telegram bot

### Suggested Change

Need to the Update readme file with the link of the telegram bot and need to enhance readme file
With the following link 
https://t.me/trackingcryptopricerbot

### Urgency

Low

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC WOB24 contributor
- [ ] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by smartfellow1234** [comment]
please checkout my pr @Harish-2003

**Comment by smartfellow1234** [comment]
please check @Harish-2003
