### ISSUE TITLE
[Feature Request]: Adding popular and new cryto listing

### ISSUE THREAD

**Issue by shreyad2806** [OpenTekHub/cryptobot#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add popular and new listing of coins for making your website that adds value to the bot and helps users stay informed about market conditions without actively watching the prices.
![WhatsApp Image 2024-10-01 at 18 45 10_2a5c7b66](https://github.com/user-attachments/assets/cf02f4eb-5c2a-4819-a8a9-20fca0e52461)
![WhatsApp Image 2024-10-01 at 18 45 30_8ac79a3f](https://github.com/user-attachments/assets/0498ec99-5b81-4427-bc40-8d23f2ec0f48)

### Use Case

This feature will help users be more connected and updated with the market trend.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC WOB24 contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by shreyad2806** [comment]
Thank you so much for considering my contribution. Do you have any suggestions for this feature or shall I continue to add feature like the screenshot?

**Comment by Harish-2003** [comment]
It's a bot not an website

**Comment by shreyad2806** [comment]
ok
