### ISSUE TITLE
Learn.md

### ISSUE THREAD

**Issue by anusha7530** [OpenTekHub/cryptobot#3]
Learn repos should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

Reference - 
- Contributing: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Contributing.md
- Learn: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Learn.md
- PROPOSAL: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/PROPOSAL.md

**Comment by Sibam-Paul** [comment]
@Harish-2003 please assign me this issue want to work on it under WoB'24

**Comment by Sibam-Paul** [comment]
@Harish-2003 Can u please help me what are the things I need to add in Learn.md

**Comment by IshuSinghSE** [comment]
Hello! Can I be assigned to this? @Harish-2003

**Comment by Harish-2003** [comment]
Add detailed description on how one can able to do contribution 
Also help them how one can able to see their bot live at telegram 
If possible try to do an detailed video on contributing as well as running this project at telegram using bot father

**Comment by Harish-2003** [comment]
> Hello! Can I be assigned to this? @Harish-2003 
> 
@Sibam-Paul is currently working on

**Comment by Sibam-Paul** [comment]
> Add detailed description on how one can able to do contribution Also help them, how one can able to see their bot live at telegram If possible try to do an detailed video on contributing as well as running this project at telegram using bot father

Ok
