### ISSUE TITLE
[Documentation Update]: Readme.md file

### ISSUE THREAD

**Issue by neeru24** [OpenTekHub/cryptobot#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I feel like Readme.md file doesn't seems attractive and is a bit boring as it contains text only.

### Suggested Change

We can use links, animations, emojis etc to enhance it 

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC WOB24 contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Harish-2003** [comment]
go ahead and make an pr referencing this issue

**Comment by neeru24** [comment]
> go ahead and make an pr referencing this issue

Hi @Harish-2003, can you add the GSSoC-ext label too.. I talked to [Kalyani Uppuluri](https://www.linkedin.com/in/ACoAAD8-cKoBRKgtLSE8wdt4e1HpUyHvflK2fKI)- leaderboard manager of GSSoC, he said that it's issue from your side, that's why it's not getting counted towrds leaderboard

**Comment by Harish-2003** [comment]
Oh ok actually I am on my phone I will do that by night

**Comment by neeru24** [comment]
> Oh ok actually I am on my phone I will do that by night

Sure
