### ISSUE TITLE
[Feature Request]: Implementing logging instead of printing errors to the console

### ISSUE THREAD

**Issue by Jordian0** [OpenTekHub/cryptobot#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the context of your Telegram bot, logging provides a way to capture important events, errors, and debugging information, helping you monitor and maintain the bot effectively

### Use Case

Log when a user requests a conversion or checks a cryptocurrency price, allowing you to analyze usage patterns over time.

### Benefits

When errors occur, logging allows you to capture the context in which they happened, making it easier to implement error recovery strategies.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC WOB24 contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by muhammedsafuvan** [comment]
can I work on this?

**Comment by Jordian0** [comment]
I want to work on this task. I'm waiting for it to be assigned to me.

**Comment by Harish-2003** [comment]
Any images?

**Comment by Jordian0** [comment]
Not really
